apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scaletestapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaletestapp
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 10  #Сперва было значение 80, с нагрузкой 10000 юзеров + прирост 100 память не доходила до лимита - поменял на 10. "Нулевой" скрин сделан при первом тесте.