http {
    upstream backend_servers {
        server backend1.example.com;
        server backend2.example.com;
        server backend3.example.com;
    }
 
    # Добавим зону хранения лимитов с ограничением 10 запросов в минуту для каждого IP

    limit_req_zone $binary_remote_addr zone=limit_zone:10m rate=10r/m;

    server {
        listen 80;
 
        location / {

            # Настройка возможного превышения лимита

            limit_req zone=limit_zone burst=0 nodelay;
            proxy_pass http://backend_servers;
        }
        
        error_page 429 = /429.html;

        location = /429.html {
            internal;
            add_header Content-Type text/html;
            return 429 "<html><body><h1>429 Too Many Requests</h1><p>Вы превысили лимит запросов. Попробуйте позже.</p></body></html>";
    }
 }

}
  